# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d2d43606df57f6371527f3f5737f9f4106e08ac581b5e150f380fcbfada35140fc37cb0a6e34a60b294500492187aa19a1a7d2f7bfef818269b4f63bf181b248

test:
  secret_key_base: 7cfa8ab910a338d193f0b7872857ae54a3945ce4ff9e188864ef68fd50ef4d3eb2d5c30e9d29b5bf24d8085016b6e5c9c5c493b68e2ca25a12c51d2cda9bcc0e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
